version: '3.4'

services:
  sapphirewebsite:
    image: sapphirewebsite
    build:
      context: sapphire-website
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
